#!/bin/bash

if [ -z "$1" ]
then
    echo "You must provide a commit message. Usage: ./deploy <commit message>"
    exit 1
fi

git add . && git commit -m "$1" && git push origin master && npm run build && firebase deploy 

